### ISSUE TITLE
Strain missing License

### ISSUE THREAD

**Issue by djbusby** [openthc/lcb-ccrs#6]
All the other files have License in the column A; not Strain.  Maybe this is just going to dump all variety into one big global dataset?  Why track them at all then?

**Comment by twilly86** [comment]
this seems by design. maybe they just want a global list of all strains people are using? they don't care if it's attached to a license.

**Comment by djbusby** [comment]
We'd uploaded 33,000 strains into this system, like at launch -- so, we're likely why others have been reporting seeing errors and or duplicates on strain data upload.

**Comment by djbusby** [comment]
This is close, won't fix.
